/**
 * Generate the requirement traceability matrix.
 *
 * Three artifacts state the same contract: the prose declares a rule, the
 * schema or the semantic phase enforces it, and a fixture pins the outcome.
 * Nothing showed those three together, so "is this rule tested" was a question
 * you answered by grepping.
 *
 * Generated rather than maintained, for the reason `catalog.json` is: a matrix
 * someone has to remember to update is a matrix that is wrong.
 *
 * NON-NORMATIVE, like everything under tools/.
 */
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import {
  discoverFamilies,
  type Family,
  isObject,
  type Json,
  REPO_ROOT,
  readJson,
  relativeToRepo,
} from './spec.ts'

const OUTPUT = join(REPO_ROOT, 'docs', 'traceability.md')

const REQUIREMENT_ID = /^[A-Z]{2,6}-[A-Z0-9]{2,12}-\d{3}$/
const ANCHOR = /<a id="([^"]+)"><\/a>/g
/** The section anchor a requirement sits under, tracked while scanning. */
const HEADING = /^#{2,3}\s+<a id="([^"]+)"><\/a>\s*([0-9.]+\s+)?(.+?)\s*$/

interface Requirement {
  readonly id: string
  readonly family: string
  readonly section: string
  readonly sectionTitle: string
  readonly specPath: string
}

function requirementsIn(family: Family): Requirement[] {
  if (!existsSync(family.specPath)) return []
  const found: Requirement[] = []
  let section = ''
  let sectionTitle = ''

  for (const line of readFileSync(family.specPath, 'utf8').split('\n')) {
    const heading = HEADING.exec(line)
    if (heading?.[1] !== undefined) {
      section = heading[1]
      sectionTitle = heading[3] ?? ''
      continue
    }
    for (const match of line.matchAll(ANCHOR)) {
      const id = match[1]
      if (id === undefined || !REQUIREMENT_ID.test(id)) continue
      found.push({
        id,
        family: family.name,
        section,
        sectionTitle,
        specPath: relativeToRepo(family.specPath),
      })
    }
  }
  return found
}

/** Requirement ID to the cases citing it, across every family's corpus. */
function citations(): Map<string, string[]> {
  const cited = new Map<string, string[]>()
  for (const family of discoverFamilies()) {
    const indexPath = join(family.conformanceDir, 'cases.json')
    if (!existsSync(indexPath)) continue
    const index = readJson(indexPath)
    const cases = isObject(index) && Array.isArray(index.cases) ? index.cases : []

    for (const entry of cases as Json[]) {
      if (!isObject(entry) || typeof entry.path !== 'string') continue
      const metadata = readJson(join(family.conformanceDir, entry.path, 'metadata.json'))
      if (!isObject(metadata) || !Array.isArray(metadata.requirements)) continue
      for (const requirement of metadata.requirements) {
        if (typeof requirement !== 'string') continue
        const label = `${family.name}/${family.major}/${entry.path}`
        cited.set(requirement, [...(cited.get(requirement) ?? []), label])
      }
    }
  }
  return cited
}

export function buildMatrix(): string {
  const cited = citations()
  const lines: string[] = [
    '# Requirement traceability',
    '',
    '**Generated by `task traceability` — do not edit.**',
    '',
    'Every requirement this specification gives a stable identifier, the clause',
    'that states it, and the conformance cases that pin it.',
    '',
    'A requirement with no case is not necessarily untested — some are excused in',
    "`tools/src/conformance.ts`'s `UNPINNED` list, each with a written reason. What",
    'this table makes visible is which rules the corpus actually holds down.',
    '',
  ]

  let total = 0
  let pinned = 0

  for (const family of discoverFamilies()) {
    const requirements = requirementsIn(family)
    if (requirements.length === 0) continue

    lines.push(`## ${family.name}/${family.major}`, '')
    lines.push('| Requirement | Clause | Cases |', '|---|---|---|')

    for (const requirement of requirements) {
      total += 1
      const cases = cited.get(requirement.id) ?? []
      if (cases.length > 0) pinned += 1

      const clause = `[§${requirement.sectionTitle}](../${requirement.specPath}#${requirement.section})`
      const links = cases.map((path) => `[\`${path}\`](../conformance/${path}/)`).join('<br>')
      lines.push(
        `| [\`${requirement.id}\`](../${requirement.specPath}#${requirement.id}) | ${clause} | ${links || '—'} |`,
      )
    }
    lines.push('')
  }

  lines.push(
    `${pinned} of ${total} requirement(s) are pinned by at least one conformance case.`,
    '',
  )
  return lines.join('\n')
}

function main(): void {
  const matrix = buildMatrix()
  writeFileSync(OUTPUT, matrix, 'utf8')
  console.log(`  ✓ ${relativeToRepo(OUTPUT)}`)
}

if (import.meta.main) main()
